#import "style.typ": heading-level-1, heading-level-2, heading-level-3

#let chapter-one() = [
  #heading-level-1("CAPÍTULO 1")

  #heading-level-2("1.1", "Introducción")

  La continuidad de los servicios digitales depende, entre otros factores, de que su infraestructura pueda actualizarse mientras atiende a sus usuarios. Corregir vulnerabilidades, incorporar funciones y modificar configuraciones son actividades necesarias durante la operación. Sin embargo, una actualización puede interrumpir comunicaciones en curso cuando exige reemplazar el proceso que las atiende. Esta dificultad adquiere especial relevancia en los proxies balanceadores de carga: programas intermediarios que reciben comunicaciones de clientes y distribuyen las solicitudes entre servidores. Por su posición, un solo proxy puede concentrar numerosas conexiones y participar tanto en el transporte de datos como en su procesamiento.

  La infraestructura de grandes plataformas permite dimensionar esta responsabilidad. En 2018, GitHub documentó un sistema que atendía decenas de miles de solicitudes por segundo y utilizaba servidores proxy basados en HAProxy, un programa de balanceo de carga @github-glb. La cantidad de solicitudes no equivale al número de conexiones, pero ilustra la escala del tráfico que atraviesa estos intermediarios. Su mantenimiento requiere distinguir dos resultados: que el servicio siga aceptando solicitudes y que cada comunicación previamente establecida pueda continuar.

  Una práctica habitual consiste en iniciar la nueva versión y dejar que la anterior termine sus conexiones, procedimiento denominado drenaje. Su duración depende de las comunicaciones pendientes. Cloudflare explicó en 2023 que Oxy, su plataforma para construir proxies en Rust, debía atender sesiones remotas y respaldos prolongados, lo que dificultaba retirar versiones anteriores cuando una corrección requería un despliegue urgente @cloudflare-oxy. Asimismo, un intercambio técnico de Fly.io registró en 2021 una espera de hasta cuatro minutos al apagar el proxy y la interrupción de transmisiones que excedían ese intervalo @fly-long-connections. Estos antecedentes muestran la tensión entre finalizar el mantenimiento y conservar conexiones de larga duración.

  La migración de conexiones aborda esa tensión al transferir su atención a otro proceso. No obstante, mantener abierta una conexión del protocolo de control de transmisión (TCP) no garantiza que una aplicación continúe correctamente: un proxy también puede conservar datos pendientes, información de cifrado y solicitudes parcialmente procesadas. La investigación aborda esta relación entre el transporte y el estado de aplicación desde las primeras propuestas de recuperación mediante migración hasta sistemas recientes de replicación de funciones de red @tcp-failover @ha-tcp. El problema de esta tesis se sitúa en ese ámbito, con énfasis en actualizaciones planificadas dentro de una misma máquina.

  Esta tesis aborda el problema mediante el desarrollo y la evaluación de una biblioteca en Rust para transferir conexiones activas entre procesos de un proxy. La biblioteca contempla TLS 1.3, el protocolo que protege la comunicación mediante cifrado, y HTTP/1.1, que organiza el intercambio de solicitudes y respuestas. Su elaboración integra competencias de la carrera de Computación: programación de sistemas, redes, concurrencia, seguridad e ingeniería de software. Estas áreas intervienen conjuntamente en la representación del estado, la coordinación entre procesos y la comprobación experimental de la continuidad. Para el sector de servicios digitales, el prototipo aporta una base técnica para estudiar mantenimientos con menos reconexiones; para sus usuarios, el beneficio potencial es evitar la interrupción de comunicaciones en curso.

  El capítulo 1 presentará el problema, su justificación, los objetivos y los antecedentes que lo sustentan. Los capítulos siguientes expondrán el diseño y la metodología de implementación y evaluación, analizarán los resultados experimentales y desarrollarán las conclusiones y recomendaciones.

  #heading-level-2("1.2", "Descripción del problema")

  Durante una actualización, el proceso anterior de un proxy conserva conexiones que la nueva instancia no puede atender únicamente por estar disponible. Si el primero termina antes de completar esas comunicaciones, los clientes necesitan reconectarse y, según la aplicación, repetir operaciones o recuperar una sesión. Si continúa mediante drenaje, su retiro queda sujeto a la duración de las conexiones. El problema consiste en transferirlas entre ambos procesos para que la versión anterior pueda finalizar y la nueva continúe la comunicación.

  Esta transferencia involucra varias capas de estado. TCP mantiene números de secuencia, ventanas y datos pendientes para entregar un flujo fiable y ordenado @rfc9293. En Linux, una conexión pertenece a un socket administrado por el núcleo, al cual el proceso accede mediante un descriptor, es decir, una referencia local a ese objeto. El proxy conserva además información en su propia memoria, como bytes ya leídos y pendientes de procesamiento. Cuando abre conexiones hacia servidores de destino, debe mantener también su asociación con las conexiones de los clientes. Conservar el socket sin esa información puede dejar al nuevo proceso con una visión incompleta de la comunicación.

  Si el proxy actúa como extremo de una comunicación cifrada con TLS 1.3, el estado incluye secretos de tráfico, números de secuencia de registros y datos de cifrado pendientes. La reanudación de una sesión TLS participa en el establecimiento de otra conexión; no continúa por sí sola una comunicación activa @rfc8446. En HTTP/1.1, el proceso puede conservar el avance del análisis de cabeceras y cuerpos, la delimitación de mensajes y el orden de respuestas pendientes @rfc9112. Por tanto, la continuidad exige preservar tanto los bytes intercambiados como el estado que permite interpretarlos.

  El proyecto considera una actualización cooperativa entre dos procesos en la misma máquina Linux, con sockets TCP del núcleo y soporte de TLS 1.3 y HTTP/1.1. La transferencia ocurre en puntos seguros: condiciones del procesamiento en las que el estado puede capturarse de forma consistente, sin operaciones concurrentes que lo modifiquen. La biblioteca debe delimitar esos puntos, coordinar el cambio de proceso responsable y detectar transferencias rechazadas o incompletas. El destino debe continuar sin pérdida, duplicación ni alteración de los datos entregados a la aplicación, y el origen debe poder retirarse después del traspaso.

  La migración requiere que el proxy y sus implementaciones de protocolos permitan acceder al estado correspondiente. El formato de intercambio debe ser compatible entre las versiones evaluadas y el canal local debe proteger el estado criptográfico. El alcance excluye el traslado entre máquinas, la recuperación ante fallos abruptos y la actualización de aplicaciones arbitrarias sin cooperación. HTTP/2 constituye una posible extensión; QUIC y HTTP/3 quedan fuera del prototipo principal. El proyecto atiende una necesidad del sector de infraestructura digital y no cuenta con una organización cliente identificada.

  El problema es observable mediante la proporción de conexiones que continúa sin reconexión, los errores de integridad, la pausa percibida por el cliente, el tiempo de migración y el tiempo necesario para retirar el proceso anterior. La evaluación distingue la espera hasta un punto seguro del tiempo efectivo de transferencia y mide el consumo adicional de procesador (CPU) y memoria. La concurrencia y el volumen de datos pendientes permiten examinar cómo cambia el comportamiento bajo distintas cargas, comparando migración, drenaje y ejecución sin actualización.

  #heading-level-2("1.3", "Justificación del problema")

  Resolver el problema permite reducir la dependencia entre la duración de las conexiones y el retiro de una versión del proxy. Esa dependencia limita el mantenimiento cuando existen comunicaciones prolongadas: esperar conserva las conexiones, mientras que imponer un plazo puede interrumpirlas. Una transferencia consistente ofrece una vía para atender ambas necesidades, aunque su costo y las condiciones que admite deben comprobarse experimentalmente.

  La literatura demuestra que migrar conexiones es viable y que existen soluciones con diferentes propósitos. SockMi estudia conexiones cifradas; PRISM aprovecha la migración para distribuir trabajo; HA/TCP conserva funciones de red mediante réplicas; MOSN incorpora transferencia de conexiones durante actualizaciones @sockmi-ssl @prism @ha-tcp @mosn-upgrade. Estos antecedentes justifican estudiar un caso delimitado: una biblioteca en Rust para actualizaciones locales, con tratamiento explícito del estado TLS 1.3 y HTTP/1.1. La contribución consiste en implementar ese componente y establecer experimentalmente sus condiciones de continuidad, sus costos y sus límites.

  Una biblioteca con interfaces de integración y restricciones conocidas permite a desarrolladores de proxies examinar qué estado necesitan exponer y qué costo introduce su transferencia. Los resultados también pueden apoyar decisiones de operadores sobre continuidad y tiempo de mantenimiento. El proyecto aporta así conocimiento aplicable al sector productivo y un ejercicio de formación que relaciona los mecanismos de redes y sistemas operativos con requisitos de software verificables. Su beneficio social potencial deriva de conservar servicios utilizados por personas y organizaciones; su utilidad se valora a partir de resultados experimentales de continuidad y costo de actualización.

  #heading-level-2("1.4", "Objetivos")

  #heading-level-3("1.4.1", "Objetivo general")

  Desarrollar y evaluar una biblioteca en Rust para migrar conexiones TCP activas entre procesos de un proxy en la misma máquina, preservando el estado necesario de TLS 1.3 y HTTP/1.1 para mantener la continuidad de la comunicación.

  #heading-level-3("1.4.2", "Objetivos específicos")

  // Se conserva el alcance de la ficha de registro y se explicita la finalidad de cada etapa.
  + Identificar el estado de TCP, TLS 1.3 y HTTP/1.1 que debe conservarse durante la migración y definir los puntos seguros de transferencia, para establecer las condiciones de continuidad de la comunicación.
  + Diseñar la arquitectura de la biblioteca y el formato de intercambio de estado entre las instancias de origen y destino del proxy, para coordinar una transferencia consistente y compatible.
  + Implementar la transferencia del socket TCP y los adaptadores necesarios para migrar el estado de TLS 1.3 y HTTP/1.1 en un proxy de demostración, para comprobar la integración del mecanismo.
  + Evaluar el prototipo mediante pruebas de continuidad de conexiones, tiempo de migración y sobrecarga durante una actualización del proxy, para determinar su efectividad y sus límites operativos.

  #heading-level-2("1.5", "Marco teórico")

  #heading-level-3("1.5.1", "Actualización de procesos y conservación de comunicaciones")

  Los mecanismos de actualización atienden distintos momentos de una comunicación. GitHub presentó multibinder para compartir sockets de escucha entre instancias de HAProxy y evitar que una recarga descartara conexiones pendientes de aceptación @github-multibinder. En 2026, Cloudflare publicó ecdysis, una biblioteca de reinicios graduales en Rust: la nueva instancia hereda los sockets de escucha, mientras la anterior completa las conexiones aceptadas @cloudflare-ecdysis. Ambos mecanismos preservan la recepción de tráfico durante el reemplazo; el drenaje mantiene temporalmente al proceso que atiende las conexiones existentes.

  La actualización dinámica de software estudia otro camino: cambiar el programa durante su ejecución y conservar su estado. Hayden y sus colaboradores presentaron Kitsune para programas en C, con puntos de actualización señalados por el desarrollador y transformaciones de datos que adaptan el estado a la nueva versión @kitsune. En su evaluación de 2012, las medianas del tiempo de actualización fueron 2,99 ms para el servidor de archivos vsftpd y 39,70 ms para Redis, un almacén de datos en memoria, en un equipo de 64 bits con procesadores Xeon E7450 y 24 GB de RAM @kitsune. Estos valores corresponden al cambio de programa, no al traspaso de un socket. El trabajo evidencia que conservar la ejecución entre versiones requiere tratar la compatibilidad del estado, además de mantener recursos abiertos.

  MOSN, una plataforma de proxies desarrollada en Go, aplica esa preocupación a actualizaciones entre procesos. Su documentación describe el envío de descriptores de conexiones, búferes de lectura y estado TLS a la nueva instancia mediante sockets de dominio Unix @mosn-upgrade. El procedimiento suspende escrituras para evitar operaciones simultáneas y contempla respuestas residuales procesadas por la versión anterior. La reconstrucción del procesamiento depende de las propiedades del protocolo y de su implementación. A diferencia del drenaje, este mecanismo permite trasladar conexiones aceptadas, pero requiere integración dentro de la plataforma.

  #heading-level-3("1.5.2", "Migración de conexiones TCP y estado de aplicación")

  La migración TCP cuenta con antecedentes anteriores a los sistemas actuales de proxies. Snoeren, Andersen y Balakrishnan propusieron en 2001 un mecanismo de recuperación que permitía trasladar conexiones a servidores alternativos @tcp-failover. La propuesta combinaba cambios al protocolo TCP con sincronización del estado de aplicación y requería soporte de transporte en los extremos. Su formulación relaciona dos problemas que reaparecen en trabajos posteriores: conservar la conexión y determinar desde qué punto puede continuar la aplicación.

  Los mecanismos posteriores también estudian la migración sin modificar al interlocutor remoto. Bernaschi, Casadei y Ruco documentaron en 2007 la migración de conexiones cifradas mediante SockMi, que combinaba un módulo del núcleo de Linux, un servicio de migración y una biblioteca para la aplicación @sockmi-ssl. El mecanismo exportaba el estado del socket y de OpenSSL, incluidas las relaciones entre sus estructuras internas, para restaurarlo en el destino. Las pruebas utilizaban OpenSSL 0.9.7i y núcleos Linux 2.4 y 2.6, con el mismo software en destino. Por su fecha, el trabajo precede a TLS 1.3; demuestra migración de comunicaciones cifradas, pero no evaluación de cambios entre versiones de un proxy.

  La captura y restauración de procesos amplía la unidad de transferencia. Yu y sus colaboradores presentaron COAT en MedComNet 2023 para conservar conexiones durante la migración de contenedores en el borde de la red @coat. Su arquitectura utiliza CRIU, una herramienta de captura y restauración de procesos en Linux, junto con Podman para administrar contenedores y una red virtual que conserva su direccionamiento mediante Open vSwitch y VXLAN. CRIU emplea el modo `TCP_REPAIR` de Linux para capturar y restaurar conexiones; la infraestructura de red mantiene su alcance después del traslado. COAT conserva el entorno de ejecución del contenedor, mientras que Kitsune trata la adaptación del estado a cambios de programa. Esta diferencia delimita dos líneas de trabajo: mover una ejecución existente y actualizar su implementación.

  #heading-level-3("1.5.3", "Transferencia de estado en funciones de red")

  Las funciones de red que procesan tráfico también mantienen estado por flujo, como las asociaciones de un balanceador o las sesiones de un proxy. Gember-Jacobson y sus colaboradores presentaron OpenNF en SIGCOMM 2014 para coordinar la transferencia de ese estado con cambios en el encaminamiento @opennf. El sistema integra interfaces de exportación e importación y controla el tráfico durante la transición para evitar inconsistencias. Su evaluación incluyó cuatro funciones de red, entre ellas el proxy Squid. El artículo reporta el traslado de 500 flujos en 215 ms, sin pérdida, con 50 ms de latencia adicional sobre los paquetes afectados @opennf. La unidad medida es una operación sobre múltiples flujos, no una migración individual.

  En NSDI 2025, Gu, Mashtizadeh y Wong presentaron HA/TCP para funciones que terminan conexiones TCP, incluidos proxies SOCKS y balanceadores @ha-tcp. El sistema replica el tráfico entrante y coordina las operaciones de sockets para que una réplica mantenga el estado necesario para asumir las conexiones. Utiliza una pila TCP de FreeBSD modificada que procesa paquetes en espacio de usuario, fuera de la ruta de red habitual del núcleo. Los autores reportan una migración de 38 µs entre réplicas previamente sincronizadas y una reducción de rendimiento inferior al 2 % en los experimentos con el proxy y el acelerador de red @ha-tcp. El tiempo de migración no incluye la detección de un fallo. A diferencia de la captura bajo demanda, este enfoque paga el costo de mantener estado replicado durante la operación.

  #heading-level-3("1.5.4", "Migración para distribuir trabajo entre servidores")

  Otra línea utiliza la transferencia de conexiones para modificar qué servidor procesa el trabajo. Hayakawa y sus colaboradores presentaron PRISM en NSDI 2021 para almacenamiento de objetos @prism. El servidor de entrada (frontend) analiza una solicitud y entrega al servidor de destino (backend) elegido la conexión TCP y el estado TLS y HTTP necesario para responder directamente al cliente. El sistema combina `TCP_REPAIR`, TLS del núcleo y un conmutador programable que cambia el encaminamiento. Su evaluación reporta 232 µs para un ciclo que libera una conexión desde un backend, la devuelve al frontend y la entrega a otro backend; 109 µs corresponden a reconstruir el estado TLS a partir de su representación transferida @prism. Estas cifras muestran la participación de las capas superiores en el costo del traspaso.

  XO, presentado por Li y sus colaboradores en NSDI 2026, estudia cómo lograr esa descarga de procesamiento con una red convencional @xo. El sistema transfiere conexiones desde un balanceador hacia servidores de destino usando `TCP_REPAIR`, estado TLS y redirección de paquetes con eBPF, un mecanismo programable de Linux. No requiere conmutadores programables y mantiene en el balanceador la redirección del tráfico entrante. En los escenarios evaluados, mejora el rendimiento entre 27 % y 365 % frente al balanceo convencional de capa de aplicación @xo. La mejora corresponde a descargar el procesamiento del intermediario. Los autores también documentan que la pausa de transferencia puede provocar retransmisiones ante solicitudes encadenadas; transferir una conexión tiene efectos observables incluso cuando el cliente no se reconecta.

  El tratamiento de paquetes que llegan durante el traspaso constituye otra diferencia entre estos sistemas. Capybara, presentado por Choi y sus colaboradores en SIGCOMM 2026, aborda la redistribución de conexiones ya establecidas frente a desequilibrios de carga @capybara. Combina un conmutador programable con una pila de red que procesa paquetes fuera del núcleo y un protocolo en dos fases que almacena tráfico durante el cambio de servidor. Sus interfaces permiten exportar estado de aplicación, incluidas solicitudes HTTP parciales y contextos TLS. En su evaluación del costo de transferencia, una migración con 75 bytes de estado TCP tarda menos de 15 µs de extremo a extremo; con 128 KB adicionales de estado TLS, menos de 60 µs @capybara. Además, en una prueba de mantenimiento con Redis y TLS, 16 conexiones necesitaron unos 200 ms para recuperar el rendimiento tras una desconexión; la migración previa al apagado mantuvo el rendimiento @capybara. Los resultados corresponden a su infraestructura y muestran tanto el costo de conservar estado como su utilidad durante el mantenimiento.

  #heading-level-3("1.5.5", "Alcances de la evidencia disponible")

  Los trabajos revisados conservan comunicaciones mediante actualización dinámica, transferencia explícita, restauración del entorno o replicación previa. Kitsune y MOSN tratan actualizaciones; COAT mueve contenedores; OpenNF y HA/TCP mantienen funciones de red; PRISM, XO y Capybara redistribuyen procesamiento, y este último también evalúa mantenimiento @kitsune @mosn-upgrade @coat @opennf @ha-tcp @prism @xo @capybara. Sus resultados miden operaciones y configuraciones diferentes, por lo que no forman una comparación directa de rendimiento.

  La conservación del transporte se complementa con la del estado superior: SockMi, PRISM y Capybara incluyen información criptográfica o de aplicación, mientras Kitsune incorpora transformaciones entre versiones @sockmi-ssl @prism @capybara @kitsune. Estos antecedentes distinguen tres aspectos de la continuidad: el traslado de TCP, la conservación de TLS y HTTP y la compatibilidad del estado entre versiones.
]
